
---
BambooBuildConnector:

    AgileCentral:
        Server    :  rally1.rallydev.com
        APIKey    :  _2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8 #yeti@rallydev.com:Vistabahn
        Workspace :  Alligators BLD Unigrations
        Lookback  :  4320 # three days # 43800 # a month

    Bamboo:
        Protocol  :  http
        Server    :  koljo03-s4576.ca.com
        Port      :  8085
        Username  :  bamboozel
        Password  :  rallydev
        AgileCentral_DefaultBuildProject :  Bamboo
        Lookback  : 43800 # a month

        Projects:
            - Project: Fernandel
              AgileCentral_Project: Rally Fernandel
              Plans:
                  - DonCamillo

    Service:
        Preview       : False
        LogLevel      : DEBUG
        MaxBuilds     : 50
        ShowVCSData   : False
        SecurityLevel: Cleartext

...
# _2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8 #yeti@rallydev.com:Vistabahn
#toto:totogithub