
---
BambooBuildConnector:

    AgileCentral:
        Server    :  rally1.rallydev.com
        APIKey    :  _2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8 #yeti@rallydev.com:Vistabahn
        Workspace :  Alligators BLD Unigrations

    Bamboo:
        Protocol  :  http
        Server    :  localhost
        Port      :  8085
        Username  :  toto
        Password  :  totogithub
        AgileCentral_DefaultBuildProject :  Bamboo

        Projects:
            - Project: Fernandel
              AgileCentral_Project: Rally Fernandel
              Plans:
                  - DonCamillo
                  - Ludovic Cruchot

    Service:
        Preview       : False
        LogLevel      : DEBUG
        MaxBuilds     : 50
        ShowVCSData   : False
        SecurityLevel: Cleartext

...
# _2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8 #yeti@rallydev.com:Vistabahn
#toto:totogithub