
---
BambooBuildConnector:

    AgileCentral:
        Server    :  rally1.rallydev.com
        APIKey    :  _2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8 #yeti@rallydev.com:Vistabahn
        Workspace :  Alligators BLD Unigrations
        Lookback  :  480

    Bamboo:
        Protocol  :  http
        Server    :  localhost
        Port      :  8085
        Username  :  toto
        Password  :  totogithub
        AgileCentral_DefaultBuildProject :  Bamboo

        Projects:
            - Project: Fernandel
              AgileCentral_Project: Rally Fernandel
              Plans:
                  - DonCamillo
                  - Ludovic Cruchot
            - Project: Cannoli
              AgileCentral_Project: Rally Fernandel
              Plans:
                  - Chocolate Cannolo
                  - No Cannolo for You

    Service:
        Preview       : True
        LogLevel      : DEBUG
        MaxBuilds     : 50
        ShowVCSData   : False

...

