
---
BambooBuildConnector:

    AgileCentral:
        Server    :  rally1.rallydev.com
        APIKey    :  _2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8
        Workspace :  Alligators BLD Unigrations

    Bamboo:
        Protocol  :  http
        Server    :  koljo03-s4576.ca.com
        Port      :  8085
        Username    :  bamboozel
        Password    :  rallydev
        AgileCentral_DefaultBuildProject :  Bamboo

        Projects:
            - Project: Fernandel
              Plans:
                  - DonCamillo


...

